config/routes.rb
Rails.application.routes.draw do
  ### Users ##
  devise_for :users, only: []

  namespace :v1, defaults: { format: :json } do
    resource :login, only: [:create], controller: :sessions
  end

  ### Root ###
  root "links#new"
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern
  include Rails.application.routes.url_helpers

  class Digitize
    @@chars = [('0'..'9'), ('a'..'z'), ('A'..'Z')].map {|r| r.to_a }.flatten
    @@n = @@chars.size
    @@chars_hash = Hash[*(@@chars).zip((0..@@n).to_a).flatten]

    class << self
      def to(i)
        digit = []
        begin
          i, c = i.divmod @@n
          digit << @@chars[c]
        end while i > 0

        return digit.reverse.join ''
      end

      def from(str)
        i = str.split('').size - 1
        r = 0
        str.split('').each_with_index do |c, n|
          r += @@n ** (i-n) * @@chars_hash[c]
        end
        r
      end
    end
  end

  included do
    after_create :generate_token
  end

  protected

  def generate_token
    self.token = Digitize.to(self.id)
    self.save
  end

  def generate_random_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
    self.save
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  include Tokenable

  belongs_to :user

  def view!
    self.view_count += 1
    self.save
  end

  def dispatchable_url
    link_url(self, host: 'http://nazr.in')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :validatable

  has_many :links

  after_create :update_access_token!

  validates :email, presence: true

  private

  def update_access_token!
    self.access_token = "#{self.id}:#{Devise.friendly_token}"
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  # protect_from_forgery with: :exception
  #
  # include ActionController::Serialization
  include AbstractController::Translation

  before_action :authenticate_user_from_token!

  respond_to :json

  def authenticate_user_from_token!
    auth_token = request.headers['Authorization']

    if auth_token
      authenticate_with_auth_token(auth_token)
    else
      authentication_error
    end
  end

  private

  def authenticate_with_auth_token(auth_token)
    unless auth_token.include?(':')
      authentication_error
      return
    end

    user_id = auth_token.split(':').first
    user = User.where(id: user_id).first

    if user && Devise.secure_compare(user.access_token, auth_token)
      # User can access
      sign_in user, store: false
    else
      authentication_error
    end
  end

  ##
  # Authentication Failure
  # Renders a 401 error
  def authentication_error
    # User's token is either invalid or not in the right format
    render json: {error: "UNAUTHORIZED"}, status: 401  # Authentication timeout
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: %i(new create show go)
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token, only: :create

  # GET /links
  def index
    @links = current_user.links
  end

  # GET /links/1
  def show
  end

  def go(token)
    @link = Link.find_by(token: token)
    @link.view!
    redirect_to @link.address, status: :moved_permanently
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  def create(link)
    @link = Link.new(link)

    if @link.save
      render text: link_url(@link)
    else
      redirect_to new_link_path
    end
  end

  # PATCH/PUT /links/1
  def update(link)
    if @link.update(link)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def dev
  end
end

app/controllers/v1/sessions_controller.rb
module V1
  class SessionsController < ApplicationController
    skip_before_action :authenticate_user_from_token!

    # POST /v1/login
    def create
      @user = User.find_for_database_authentication(email: params[:username])
      return invalid_login_attempt unless @user

      if @user.valid_password?(params[:password])
        sign_in :user, @user
        render json: @user, serializer: SessionSerializer, root: nil
      else
        invalid_login_attempt
      end
    end

    private

    def invalid_login_attempt
      warden.custom_failure!
      render json: {error: 'sessions_controller.invalid_login_attempt'}, status: :unprocessable_entity
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge, chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'
    meta name='description' content='ナズーリン好きのための小さな小さなURL短縮サービス'
    meta name='keywords' content='nazr.in, ナズーリン, 小さな小さなURL短縮サービス, URL短縮サービス, 短縮URLサービス'
    meta name='apple-mobile-web-app-title' content='nazr.in'
    link rel='canonical' href='http://nazr.in'
    title nazr.in

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    p.notice = notice
    p.alert = alert

    header

    .wrapper
      = yield

    = render partial: 'shared/google_analytics'

app/views/links/_form.html.slim
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      h2 = "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      ul
        - @link.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :address

  .action
    = f.submit 'Save'

app/views/links/edit.html.slim
h1 Editing link

== render 'form'

= link_to 'Show', @link
'|
= link_to 'Back', links_path

app/views/links/index.html.slim
h1 Listing links

table
  thead
    tr
      th Generated url
      th
      th
      th

  tbody
    - @links.each do |link|
      tr
        td = link.generated_url
        td = link_to 'Show', link
        td = link_to 'Edit', edit_link_path(link)
        td = link_to 'Destroy', link, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Link', new_link_path

app/views/links/new.html.slim
section.promo
  a href="/"
    = image_tag 'logo_doodle1.png', class: :logo
  = form_for @link, action: :create, html: { class: :shorten_form } do |f|
    .input-group
      .address-field
        = f.text_field :address, class: 'text-field'
        = f.button class: 'submit-button' do
          i.fa.fa-angle-right

  .group-large
    ul.horizontal
      li = link_to static_pages_about_url(subdomain: 'docs') do
        i.fa.fa-question-circle
        | &nbsp;nazr.inとはなんですか？
      - if user_signed_in?
        li = link_to destroy_user_session_path, method: :delete do
          i.fa.fa-sign-out
          | &nbsp;ログアウト
      - else
        li = link_to new_user_session_path do
          i.fa.fa-sign-in
          | &nbsp;ログイン

app/views/links/show.html.slim
p#notice = notice

p
  = @link.address

= link_to 'Edit', edit_link_path(@link)
'|
= link_to 'Back', links_path

app/views/shared/_google_analytics.slim
javascript:
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28919359-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/static_pages/about.html.slim
h1 nazr.in とは

p nazr.in(読み方: ナズーリン) 「ナズーリン好きのための短縮URLサービス」です。ナズーリン好きでない方もナズーリンが好きになること請け合いです。

h2 開発者の方へ

p nazr.inは開発者向けにAPIを公開しております。詳しくはこちらのドキュメントをご覧下さい。

h3 つくった人について

dl
  dt UIデザイン・コーディング
  dd おおあめ - @o_ame
  dt ロゴをかいた人
  dd 川科 - @kahasina9

app/views/users/shared/_links.slim
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    br